-- Create the house_info table
create table if not exists public.house_info (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  value text not null,
  category text default 'Generelt', -- e.g., 'Wifi', 'Nøgle', 'Praktisk'
  icon text -- Optional: Lucide icon name
);

-- Enable Row Level Security (RLS)
alter table public.house_info enable row level security;

-- Create policy to allow read access for authenticated users only
create policy "Enable read access for authenticated users"
on public.house_info
for select
to authenticated
using (true);

-- Create policy to allow insert/update/delete for authenticated users
-- (In a stricter app, this might be limited to specific admin users)
create policy "Enable write access for authenticated users"
on public.house_info
for all
to authenticated
using (true)
with check (true);

-- Insert some example data (User can edit this later)
insert into public.house_info (title, value, category, icon)
values 
  ('Wifi Navn', 'Skovkrogen_Guest', 'Internet', 'Wifi'),
  ('Wifi Kode', 'sommerhus2024', 'Internet', 'Lock'),
  ('Nøgleboks', '1234', 'Adgang', 'Key');
