-- Create bookings table
create table bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  start_date date not null,
  end_date date not null,
  guest_name text not null,
  guest_email text not null,
  guest_count integer default 1 not null,
  allow_other_family boolean default false not null,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled'))
);

-- Enable Row Level Security
alter table bookings enable row level security;

-- Create policies
-- Allow anyone to read bookings (to see availability)
create policy "Public bookings are viewable by everyone"
  on bookings for select
  using ( true );

-- Allow anyone to insert bookings (public booking form)
create policy "Anyone can create a booking"
  on bookings for insert
  with check ( true );

-- Only authenticated users can update/delete (admin)
-- Assuming you will use Supabase Auth for admin panel later, or just use the dashboard for now.
-- For now, we can leave update/delete restricted to service role or authenticated users if you set that up.
create policy "Authenticated users can update bookings"
  on bookings for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete bookings"
  on bookings for delete
  using ( auth.role() = 'authenticated' );
